### ISSUE TITLE
Error printing labels 

### ISSUE THREAD

**Issue by frakman1** [mclarkk/lifxlan#1]
I have three bulbs but I know that they all have labels. I also know that they are running firmware 2.0

In verbose_lan.py. When I run it on my Mac using (python verbose_lan.py) , I get several pages of verbose message dumps and then finally:
```
Found Bulbs:
Traceback (most recent call last):
  File "verbose_lan.py", line 29, in <module>
    main()
  File "verbose_lan.py", line 26, in main
    print("  " + label)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I tried changing that line to: 
```
print(" %s " % label) 
```
instead but that ended up giving me:
```
Found Bulbs:
 None 
 None 
 None 
```

I also tried hello_world.py and also ran into trouble printing the bulbs:
```
$ python hello_world.py 3
Discovering lights...

Found 3 light(s):

Did not receive <class 'lifxlan.msgtypes.LightStatePower'> in response to <class 'lifxlan.msgtypes.LightGetPower'>
Traceback (most recent call last):
  File "hello_world.py", line 26, in <module>
    main()
  File "hello_world.py", line 23, in main
    print(d)
  File "/Library/Python/2.7/site-packages/lifxlan/light.py", line 88, in __str__
    s = self.device_characteristics_str(indent)
  File "/Library/Python/2.7/site-packages/lifxlan/device.py", line 253, in device_characteristics_str
    s += indent + "Power: {}\n".format(STR_MAP[self.power_level])
KeyError: None
```

**Comment by mclarkk** [comment]
I fixed the last issue with the power level and printing the label. However, I'm not yet sure what is causing all of the device labels to be None. Based on the "Did not receive..." message, I'm guessing the client isn't always receiving responses back from the lights before it times out/maxes out its attempts. 

Could you run hello_world.py (with the fix, you'll need to git pull and sudo python setup.py install first) and paste the output here? That should show me the wifi signal strength of your bulbs. 

Could you also copy and paste all messages having to do with GetLabel and StateLabel messages from verbose_lan.py (should be the last few)? That should also confirm that the issue is that the client is not receiving the responses in time.

**Comment by frakman1** [comment]
Seems to work much better now. Thanks!
```
$ python hello_world.py 3
Discovering lights...

Found 3 light(s):

AC-2
  MAC Address: d0:73:d5:00:96:fa
  Port: 56700
  Service: UDP
  Power: On
  Color (HSBK): (50971, 0, 65535, 4998)
  Host Firmware Build Timestamp: 1421032521000000000 (2015-01-12 03:15:21 UTC)
  Host Firmware Build Version: 131072
  Wifi Firmware Build Timestamp: 1420435246000000000 (2015-01-05 05:20:46 UTC)
  Wifi Firmware Build Version: 131072
  Vendor: 1
  Product: 1
  Version: 6
  Current Time: 1436377839344000004 (2015-07-08 17:50:39 UTC)
  Uptime (ns): 54970285000000 (15.27 hours)
  Last Downtime Duration +/-5s (ns): 4000 (0.0 hours)
  Wifi Signal Strength (mW): 0.000199526213692
  Wifi TX (bytes): 53641
  Wifi RX (bytes): 212414

Desk1
  MAC Address: d0:73:d5:03:19:e3
  Port: 56700
  Service: UDP
  Power: On
  Color (HSBK): (50971, 0, 65535, 4998)
  Host Firmware Build Timestamp: 1421032521000000000 (2015-01-12 03:15:21 UTC)
  Host Firmware Build Version: 131072
  Wifi Firmware Build Timestamp: 1420435246000000000 (2015-01-05 05:20:46 UTC)
  Wifi Firmware Build Version: 131072
  Vendor: 1
  Product: 1
  Version: 6
  Current Time: 1436377839396000004 (2015-07-08 17:50:39 UTC)
  Uptime (ns): 54462068000000 (15.13 hours)
  Last Downtime Duration +/-5s (ns): 4000 (0.0 hours)
  Wifi Signal Strength (mW): 0.000398107076762
  Wifi TX (bytes): 41963
  Wifi RX (bytes): 146266

AC
  MAC Address: d0:73:d5:01:73:e9
  Port: 56700
  Service: UDP
  Power: On
  Color (HSBK): (50971, 0, 65535, 4998)
  Host Firmware Build Timestamp: 1421032521000000000 (2015-01-12 03:15:21 UTC)
  Host Firmware Build Version: 131072
  Wifi Firmware Build Timestamp: 1420435246000000000 (2015-01-05 05:20:46 UTC)
  Wifi Firmware Build Version: 131072
  Vendor: 1
  Product: 1
  Version: 6
  Current Time: 1436377840228000004 (2015-07-08 17:50:40 UTC)
  Uptime (ns): 54962074000000 (15.27 hours)
  Last Downtime Duration +/-5s (ns): 4000 (0.0 hours)
  Wifi Signal Strength (mW): 3.98107076762e-05
  Wifi TX (bytes): 55211
  Wifi RX (bytes): 211599


$ python verbose_lan.py 3
SEND: GetService
  Size: 36
  Origin: 0
  Tagged: 1
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: 00:00:00:00:00:00
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 2
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x34', '0x43', '0x73', '0xdf', '0x91', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x2', '0x0', '0x0', '0x0']

RECV: GetService
  Size: 36
  Origin: 0
  Tagged: 1
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: 00:00:00:00:00:00
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 2
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x34', '0x43', '0x73', '0xdf', '0x91', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x2', '0x0', '0x0', '0x0']

RECV: StateService
  Size: 41
  Origin: 1
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:00:96:fa
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 3
  Payload:
    Service: 1
    Port: 56700
  Bytes:
    ['0x29', '0x0', '0x0', '0x54', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x0', '0x96', '0xfa', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0xc4', '0xd9', '0xf6', '0x70', '0x1e', '0xa', '0xef', '0x13', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

RECV: StateService
  Size: 41
  Origin: 1
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:01:73:e9
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 3
  Payload:
    Service: 1
    Port: 56700
  Bytes:
    ['0x29', '0x0', '0x0', '0x54', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x1', '0x73', '0xe9', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0xc4', '0x72', '0xfb', '0x37', '0x1e', '0xa', '0xef', '0x13', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

RECV: StateService
  Size: 41
  Origin: 1
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:03:19:e3
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 3
  Payload:
    Service: 1
    Port: 56700
  Bytes:
    ['0x29', '0x0', '0x0', '0x54', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x3', '0x19', '0xe3', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0x4', '0x7b', '0x49', '0x3d', '0x1e', '0xa', '0xef', '0x13', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

Discovering lights...
SEND: GetLabel
  Size: 36
  Origin: 0
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:00:96:fa
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 23
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x14', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x0', '0x96', '0xfa', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x17', '0x0', '0x0', '0x0']

RECV: GetLabel
  Size: 36
  Origin: 0
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:00:96:fa
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 23
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x14', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x0', '0x96', '0xfa', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x17', '0x0', '0x0', '0x0']

RECV: StateLabel
  Size: 68
  Origin: 1
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:00:96:fa
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 25
  Payload:
    Label: AC-2
  Bytes:
    ['0x44', '0x0', '0x0', '0x54', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x0', '0x96', '0xfa', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0xc4', '0xa4', '0x1f', '0x7d', '0x1e', '0xa', '0xef', '0x13', '0x19', '0x0', '0x0', '0x0', '0x41', '0x43', '0x2d', '0x32', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0']

SEND: GetLabel
  Size: 36
  Origin: 0
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:01:73:e9
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 23
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x14', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x1', '0x73', '0xe9', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x17', '0x0', '0x0', '0x0']

RECV: GetLabel
  Size: 36
  Origin: 0
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:01:73:e9
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 23
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x14', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x1', '0x73', '0xe9', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x17', '0x0', '0x0', '0x0']

RECV: StateLabel
  Size: 68
  Origin: 1
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:01:73:e9
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 25
  Payload:
    Label: AC
  Bytes:
    ['0x44', '0x0', '0x0', '0x54', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x1', '0x73', '0xe9', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0x4', '0x4b', '0x5c', '0x50', '0x1e', '0xa', '0xef', '0x13', '0x19', '0x0', '0x0', '0x0', '0x41', '0x43', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0']

SEND: GetLabel
  Size: 36
  Origin: 0
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:03:19:e3
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 23
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x14', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x3', '0x19', '0xe3', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x17', '0x0', '0x0', '0x0']

RECV: GetLabel
  Size: 36
  Origin: 0
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:03:19:e3
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 23
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x14', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x3', '0x19', '0xe3', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x17', '0x0', '0x0', '0x0']

RECV: StateLabel
  Size: 68
  Origin: 1
  Tagged: 0
  Protocol: 1024
  Source ID: 2447340355
  Target MAC Address: d0:73:d5:03:19:e3
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 25
  Payload:
    Label: Desk1
  Bytes:
    ['0x44', '0x0', '0x0', '0x54', '0x43', '0x73', '0xdf', '0x91', '0xd0', '0x73', '0xd5', '0x3', '0x19', '0xe3', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0x84', '0x60', '0xe2', '0x61', '0x1e', '0xa', '0xef', '0x13', '0x19', '0x0', '0x0', '0x0', '0x44', '0x65', '0x73', '0x6b', '0x31', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0']

Found Bulbs:
  AC-2
  AC
  Desk1
$ 
```

**Comment by mclarkk** [comment]
Yay! Glad it's working now.
