### ISSUE TITLE
Unable to discover lights

### ISSUE THREAD

**Issue by ShadowXVII** [mclarkk/lifxlan#101]
I have a handful of LIFX bulbs: 2x LIFX Original, 1x LIFX Color 1000 and 4x LIFX DL.

I ran `verbose_lan.py`, and got the following output, however **Found Bulbs** comes back empty.
Any ideas why it's not being parsed correctly? I tried parsing the bytes but couldn't quite get the format down.

I did get 10 packets, but I've included the 7 unique packets.

## Dump
Discovery will go much faster if you provide the number of lights on your LAN:
  python verbose_lan.py <number of lights on LAN>

Discovering lights...
SEND: GetService
  Size: 36
  Origin: 0
  Tagged: 1
  Protocol: 1024
  Source ID: 19946
  Target MAC Address: 00:00:00:00:00:00
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 2
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x34', '0xea', '0x4d', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x2', '0x0', '0x0', '0x0']

RECV: Message
  Size: 10496
  Origin: 0
  Tagged: 0
  Protocol: 20
  Source ID: 3930914816
  Target MAC Address: d0:73:d5:27:b2:ae
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 768
  Payload:
    <empty>
  Bytes:
    ['0x29', '0x0', '0x0', '0x14', '0xea', '0x4d', '0x0', '0x0', '0xd0', '0x73', '0xd5', '0x27', '0xb2', '0xae', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x1', '0x0', '0x0', '0x2a', '0x7b', '0x39', '0x2c', '0x80', '0x1', '0x0', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

RECV: Message
  Size: 10496
  Origin: 0
  Tagged: 0
  Protocol: 20
  Source ID: 3930914816
  Target MAC Address: d0:73:d5:12:56:28
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 768
  Payload:
    <empty>
  Bytes:
    ['0x29', '0x0', '0x0', '0x14', '0xea', '0x4d', '0x0', '0x0', '0xd0', '0x73', '0xd5', '0x12', '0x56', '0x28', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x1', '0x0', '0xc8', '0xa9', '0x9c', '0xfc', '0x8b', '0xab', '0x20', '0x15', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

RECV: Message
  Size: 10496
  Origin: 0
  Tagged: 0
  Protocol: 20
  Source ID: 3930914816
  Target MAC Address: d0:73:d5:27:80:a4
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 768
  Payload:
    <empty>
  Bytes:
    ['0x29', '0x0', '0x0', '0x14', '0xea', '0x4d', '0x0', '0x0', '0xd0', '0x73', '0xd5', '0x27', '0x80', '0xa4', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x1', '0x0', '0x40', '0xd2', '0xee', '0x64', '0x2c', '0x80', '0x1', '0x0', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

RECV: Message
  Size: 10496
  Origin: 0
  Tagged: 0
  Protocol: 20
  Source ID: 3930914816
  Target MAC Address: d0:73:d5:25:d1:77
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 768
  Payload:
    <empty>
  Bytes:
    ['0x29', '0x0', '0x0', '0x14', '0xea', '0x4d', '0x0', '0x0', '0xd0', '0x73', '0xd5', '0x25', '0xd1', '0x77', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x1', '0x0', '0xc0', '0x53', '0x3f', '0xff', '0x2b', '0x80', '0x1', '0x0', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

RECV: Message
  Size: 10496
  Origin: 0
  Tagged: 0
  Protocol: 20
  Source ID: 3930914816
  Target MAC Address: d0:73:d5:27:bd:b1
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 768
  Payload:
    <empty>
  Bytes:
    ['0x29', '0x0', '0x0', '0x14', '0xea', '0x4d', '0x0', '0x0', '0xd0', '0x73', '0xd5', '0x27', '0xbd', '0xb1', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x1', '0x0', '0x80', '0xab', '0xdd', '0x4d', '0x2c', '0x80', '0x1', '0x0', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

RECV: Message
  Size: 10496
  Origin: 0
  Tagged: 0
  Protocol: 84
  Source ID: 3930914816
  Target MAC Address: d0:73:d5:00:bd:16
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 768
  Payload:
    <empty>
  Bytes:
    ['0x29', '0x0', '0x0', '0x54', '0xea', '0x4d', '0x0', '0x0', '0xd0', '0x73', '0xd5', '0x0', '0xbd', '0x16', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0xc4', '0xa3', '0x85', '0xdb', '0x8b', '0xab', '0x20', '0x15', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

RECV: Message
  Size: 10496
  Origin: 0
  Tagged: 0
  Protocol: 84
  Source ID: 3930914816
  Target MAC Address: d0:73:d5:03:47:c4
  Ack Requested: 0
  Response Requested: 0
  Seq Num: 0
  Message Type: 768
  Payload:
    <empty>
  Bytes:
    ['0x29', '0x0', '0x0', '0x54', '0xea', '0x4d', '0x0', '0x0', '0xd0', '0x73', '0xd5', '0x3', '0x47', '0xc4', '0x0', '0x0', '0x4c', '0x49', '0x46', '0x58', '0x56', '0x32', '0x0', '0x0', '0xc4', '0xc1', '0x1', '0x5', '0x8c', '0xab', '0x20', '0x15', '0x3', '0x0', '0x0', '0x0', '0x1', '0x7c', '0xdd', '0x0', '0x0']

Found Bulbs:

**Comment by ShadowXVII** [comment]
Some additional notes;
- The generic broadcast functions appear to work fine and are picked up by all the globes.
- Direct addressing using Light(mac,ip) appears to work on all bulbs, but I get the exception (included below) when running set_color from all bulbs no matter if it succeeded or not.
- Discovery comes up empty, get_lights, etc returns an empty array (the examples then fail with an index out of bounds attempting to use [0])

### Python exception from all bulbs
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    light2.set_color(GREEN,2000,False)
  File "/usr/lib/python2.7/site-packages/lifxlan/light.py", line 82, in set_color
    self.req_with_ack(LightSetColor, {"color": color, "duration": duration})
  File "/usr/lib/python2.7/site-packages/lifxlan/device.py", line 471, in req_with_ack
    self.req_with_resp(msg_type, Acknowledgement, payload, timeout_secs, max_attempts)
  File "/usr/lib/python2.7/site-packages/lifxlan/device.py", line 520, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.Acknowledgement'>] from d0:73:d5:25:d1:77 (Name: None) in response to <class 'lifxlan.msgtypes.LightSetColor'>
```

**Comment by mclarkk** [comment]
Wow, those messages look...weird. I don't understand why the message type is 768 instead of 3 (StateService), or why the size, protocol, and source ID of the responses are wrong too (should be 41, 1024, and 19946, respectively). The packets themselves in byte form look correct, so there is something SUPER weird happening when the library is trying to interpret the bytes as data.

What hardware and operating system are you using? How did you install the library?

**Comment by mclarkk** [comment]
Ahhh gawdddd, it's because the endianness of the machine is different. The part of the library that uses C structs is reading the bytes in reverse. I'm working on a fix!

**Comment by mclarkk** [comment]
All right, I just pushed a update to the repo that specifies the endianness explicitly instead of defaulting to the native architecture. Pull and reinstall from source (if you originally installed from pip, remember to uninstall that version first). Let me know if that fixes it for you!

**Comment by ShadowXVII** [comment]
Thanks for reviewing them -- it's running on an Arduino Yun, which uses a LEDE/OpenWrt image. 
I'll pull the latest changes and try them out, thanks :)

**Comment by mclarkk** [comment]
Have you been able to see yet if the new changes work?

**Comment by ShadowXVII** [comment]
I checked out the latest library and was able to discover some bulbs using verbose_lan.py.
Some bulbs aren't seen -- get about 4 of 7 showing at any one time.

Some of other other examples (e.g. rainbow.py, blink.py) seem to fail.
I had this result with blink.py;
```
Discovering lights...
Selected Lounge-4
Toggling power...
Traceback (most recent call last):
  File "blink.py", line 74, in <module>
    main()
  File "blink.py", line 37, in main
    toggle_device_power(bulb, 0.2)
  File "blink.py", line 57, in toggle_device_power
    device.set_power("on", rapid)
  File "/usr/lib/python2.7/site-packages/lifxlan/light.py", line 52, in set_power
    self.req_with_ack(LightSetPower, {"power_level": 65535, "duration": duration})
  File "/usr/lib/python2.7/site-packages/lifxlan/device.py", line 471, in req_with_ack
    self.req_with_resp(msg_type, Acknowledgement, payload, timeout_secs, max_attempts)
  File "/usr/lib/python2.7/site-packages/lifxlan/device.py", line 520, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.Acknowledgement'>] from d0:73:d5:27:bd:b1 (Name: Lounge-4) in response to <class 'lifxlan.msgtypes.LightSetPower'>

```

**Comment by mclarkk** [comment]
What are the types of bulbs that aren't seen? 
Have you powered them off and then powered them back on again? 
What firmware are the bulbs running? Could you paste the output of "hello_world.py" here?

**Comment by mclarkk** [comment]
(My guess is just that the Yun is slow and increasing the DEFAULT_TIMEOUT in `device.py` should help. You could also try increasing the DEFAULT_ATTEMPTS, but I'd play around with the timeout first.)

**Comment by mclarkk** [comment]
Closing for inactivity, but feel free to reopen!

**Comment by frakman1** [comment]
Just a note/suggestion. It would be nice if the timeout could be an input parameter to the discover/init function. That way people could just use the pip install instead of tweaking your library's code directly.

**Comment by frakman1** [comment]
Just a note/suggestion. It would be nice if the timeout could be an input parameter to the discover/init function. That way people could just use the pip install instead of tweaking your library's code directly. My apologies if this is already implemented and I missed it.

**Comment by Reasel** [comment]
So I just ran into this problem and it was fixed by uninstalling the pip version and installing from source. before I was getting a very similar output to OP.
