### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'L'

### ISSUE THREAD

**Issue by autolog** [mclarkk/lifxlan#103]
Installed the latest version of the library = 1.2.4

I am testing on Mac OS High Sierra, running Python 2.7.10 in a terminal session.

I can discover the LIFX devices and display their MAC addresses.
If I try and retrieve the lamp labels, I am getting the following error (terminal output):

Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> from lifxlan import LifxLAN
>>> num_lights = None
>>> lifx = LifxLAN(num_lights)
>>> devices = lifx.get_lights()
>>> print len(devices)
15
>>> print("MAC: {}".format(devices[5].mac_addr))
MAC: d0:73:d5:AA:BB:CC **<PARTIALLY REDACTED>**

>>> print("MAC: {}".format(devices[5].get_label()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/lifxlan/device.py", line 138, in get_label
    response = self.req_with_resp(GetLabel, StateLabel)
  File "/Library/Python/2.7/site-packages/lifxlan/device.py", line 504, in req_with_resp
    response = unpack_lifx_message(data)
  File "/Library/Python/2.7/site-packages/lifxlan/unpack.py", line 111, in unpack_lifx_message
    message = StateLabel(target_addr, source_id, seq_num, payload, ack_requested, response_requested)
  File "/Library/Python/2.7/site-packages/lifxlan/msgtypes.py", line 186, in __init__
    super(StateLabel, self).__init__(MSG_IDS[StateLabel], target_addr, source_id, seq_num, ack_requested, response_requested)
  File "/Library/Python/2.7/site-packages/lifxlan/message.py", line 43, in __init__
    self.packed_message = self.generate_packed_message()
  File "/Library/Python/2.7/site-packages/lifxlan/message.py", line 46, in generate_packed_message
    self.payload = self.get_payload()
  File "/Library/Python/2.7/site-packages/lifxlan/msgtypes.py", line 191, in get_payload
    label = b"".join(little_endian(bitstring.pack("8", c)) for c in self.label.encode())
  File "/Library/Python/2.7/site-packages/lifxlan/msgtypes.py", line 191, in <genexpr>
    label = b"".join(little_endian(bitstring.pack("8", c)) for c in self.label.encode())
  File "/Library/Python/2.7/site-packages/bitstring.py", line 4224, in pack
    s._append(BitStream._init_with_token(name, length, value))
  File "/Library/Python/2.7/site-packages/bitstring.py", line 1224, in _init_with_token
    b = cls(**{name: int(value), 'length': token_length})
ValueError: invalid literal for int() with base 10: 'L'
>>> 

The name of the lamp (just added via the iOS LIFX App) is "LIFX DLight AABBCC"

From testing with other lamps, I think its is failing somehow on the first character of the label.

It also fails on get_color().

The previous version of the library I was using (dated around August last year), still works OK i.e. discovers devices and all details accessible.

**Comment by mclarkk** [comment]
Yeah, there was a change made to support unicode. It works in Python 3. I'll look into seeing why it doesn't work for Python 2 and what it would take to make it work for both...

**Comment by mclarkk** [comment]
Made some fixes, so now there is unicode support in both Python 3 and Python 2 and nothing should choke anymore! I pushed the new version to pip. Let me know how it works for you!

Thanks for pointing this major issue out. I thought that I had tested the previous changes with Python 2, but clearly not!

**Comment by autolog** [comment]
Installed 1.2.5 and now all OK. 👍 

Thanks for the quick fix :)
