### ISSUE TITLE
Odd-length string error during discovery

### ISSUE THREAD

**Issue by danbri** [mclarkk/lifxlan#11]
e.g. 

    Discovering lights...
    Traceback (most recent call last):
      File "get_color_all.py", line 27, in <module>
        main()
      File "get_color_all.py", line 24, in main
        print("{} ({}) HSBK: {}".format(d.get_label(), d.mac_addr, d.get_color()))
      File "/Library/Python/2.7/site-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/light.py", line 71, in get_color
        response = self.req_with_resp(LightGet, LightState)
      File "/Library/Python/2.7/site-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/device.py", line 352, in req_with_resp
        response = unpack_lifx_message(data)
      File "/Library/Python/2.7/site-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/unpack.py", line 154, in unpack_lifx_message
        label = binascii.unhexlify("".join(["%x" % (b & 0x000000ff) for b in struct.unpack("b"*32, payload_str[12:44])]))
    TypeError: Odd-length string

**Comment by Fossadouglasi** [comment]
I had the same problem. I tracked it down to the lamp label. The unpack.py dowsnt work if the lamp name has an odd number of characters. So just change the lamp names if you need a quick fix. 
Of course the base issue still remains :)

**Comment by lovelytwo** [comment]
In unpack.py modify all %x to %2.2x 
all ascii characters are two digits long, were as the padding is one digit long, so you end up with odd number of padding with odd numbers of characters.

**Comment by Cbeck527** [comment]
@Fossadouglasi @lovelytwo https://github.com/mclarkk/lifxlan/pull/12 should fix it!

**Comment by GeorgeHahn** [comment]
I just changed line 154 of `unpack.py` to

```        label = payload_str[12:44].strip("\0")```

**Comment by mclarkk** [comment]
Fixed with a pull request! Thanks!
