### ISSUE TITLE
Bulb does not send any packets back.

### ISSUE THREAD

**Issue by Rtyui** [mclarkk/lifxlan#112]
Hi i recently got a lifx bulb and i'm trying to control it with this python module. First time i tried a simple discovery and power set and it worked from a rasperry pi but recently i started to write more complex code on my laptop for the system and noticed that i can't find the bulb anymore neither from laptop or raspberry.

I went through all the issues that people had and it seems i some cannot understand and some does not solve my problem.
I tried to hardware reset the bulb, make sure to download the latest patch and seems like a deeper problem with my bulb.

When discovering with get_lights function i do not get any (well i have only one but u get it) because the program does not recieve any message and when initializing with mac and ip i can set stuff but only without requesting acknowledge cuz that would result in an error.

Discovery run:
SEND: GetService
  Size: 36
  Origin: 1
  Tagged: 1
  Protocol: 1024
  Source ID: 26719
  Target MAC Address: 00:00:00:00:00:00
  Ack Requested: 0
  Response Requested: 1
  Seq Num: 0
  Message Type: 2
  Payload:
    <empty>
  Bytes:
    ['0x24', '0x0', '0x0', '0x74', '0x5f', '0x68', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x1', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x2', '0x0', '0x0', '0x0']

list is: []

Set with acknowledge:
Traceback (most recent call last):
  File "test2.py", line 8, in <module>
    l.set_power('off')
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/light.py", line 56, in set_power
    self.req_with_ack(LightSetPower, {"power_level": 0, "duration": duration})
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/device.py", line 477, in req_with_ack
    self.req_with_resp(msg_type, Acknowledgement, payload, timeout_secs, max_attempts)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan/device.py", line 526, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.Acknowledgement'>] from d0:73:d5:00:6c:36 (Name: None) in response to <class 'lifxlan.msgtypes.LightSetPower'>

**Comment by mclarkk** [comment]
I'm sorry to hear about that! What kind of network are you on? Is it a typical home network with one router and one NAT'd subnet, or do you have some special going on with your networking setup?

**Comment by Rtyui** [comment]
Thank you for the response!

As a matter of fact i can see the bulb in the LAN. I can ping it from my laptop. My home setup is just based on a router. The most annoying fact is that the first time i ran the simple software of discovery it worked and it return the list with the single bulb that i have. The network is as simple as possible. And the application from lifx works, so i doubt that there is a problem with the bulb at all. I also tried some fixes that i found in other threads like hard and soft resetting the bulb or many others.

If you have any other idea or tests that i should try i'm open to suggestions. Thanks again.

**Comment by mclarkk** [comment]
Are you on a Windows computer? If so, #114 might be relevant to you. It could be that during discovery, the computer's firewall settings are blocking responses to the port that the light is trying to communicate with. The easiest way to test and see if that is the case is probably to temporarily disable the computer's firewall while on your home network (if you trust all the devices on that network...and don't forget to turn it back on) and see if that fixes the discovery issue. If that does fix it, I can make some changes in the library that'll help you out.
