### ISSUE TITLE
Need more detailed installation instructions

### ISSUE THREAD

**Issue by kylegoetz** [mclarkk/lifxlan#13]
I created a virtualenv, loaded it, then ran "pip install lifxlan." It installed correctly. However, when I try to import lifxlan, I get:

Python 3.4.0 (v3.4.0:04f714765c13, Mar 15 2014, 23:02:41) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lifxlan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kylegoetz/Documents/Workspaces/lifx/venv/lib/python3.4/site-packages/lifxlan-0.2.3-py3.4.egg/lifxlan/__init__.py", line 1, in <module>
    from .lifxlan import LifxLAN
  File "/Users/kylegoetz/Documents/Workspaces/lifx/venv/lib/python3.4/site-packages/lifxlan-0.2.3-py3.4.egg/lifxlan/lifxlan.py", line 5, in <module>
    from message import BROADCAST_MAC, BROADCAST_SOURCE_ID
ImportError: No module named 'message'

Cloning the repo and executing hello_world.py sample script I get the same problem:

Traceback (most recent call last):
  File "hello_world.py", line 2, in <module>
    from lifxlan import *
  File "/Users/kylegoetz/Documents/Workspaces/lifx/venv/lib/python3.4/site-packages/lifxlan-0.2.3-py3.4.egg/lifxlan/__init__.py", line 1, in <module>
    from .lifxlan import LifxLAN
  File "/Users/kylegoetz/Documents/Workspaces/lifx/venv/lib/python3.4/site-packages/lifxlan-0.2.3-py3.4.egg/lifxlan/lifxlan.py", line 5, in <module>
    from message import BROADCAST_MAC, BROADCAST_SOURCE_ID
ImportError: No module named 'message'

Even by doing the python setup.py install the problem persists.

**Comment by kylegoetz** [comment]
Never mind. This module is only for Python 2. I forked, updated the readme to reflect this, and made a PR.

**Comment by ceboxsell** [comment]
Run it past the Python3 script 2to3. if you want to try python 3.5

**Comment by kylegoetz** [comment]
Actually it looks like someone else has ported it and filed a PR with you.

**Comment by mclarkk** [comment]
Pull request accepted, thanks! Check out https://github.com/moonwatcher/lifxlan for a Python 3 port.
