### ISSUE TITLE
Linux lifxlan.device.WorkflowException

### ISSUE THREAD

**Issue by mikevador02** [mclarkk/lifxlan#65]
Hello

I tried to use your project.

i have error when i try to run in python2 

i lauch braodcast.py is ok
python2 broadcast_on.py
or off, color work wel (turn off or on or color my lifx bulb)

after i try an exemple one bulb parameter:

 python2 blink.py 1

Discovering lights...
Selected None
Traceback (most recent call last):
  File "blink.py", line 72, in <module>
    main()
  File "blink.py", line 29, in main
    original_color = bulb.get_color()
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/light.py", line 71, in get_color
    response = self.req_with_resp(LightGet, LightState)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/device.py", line 349, in req_with_resp
    response = unpack_lifx_message(data)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/unpack.py", line 156, in unpack_lifx_message
    message = LightState(target_addr, source_id, seq_num, payload, ack_requested, response_requested)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/msgtypes.py", line 306, in __init__
    super(LightState, self).__init__(MSG_IDS[LightState], target_addr, source_id, seq_num, ack_requested, response_requested)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/message.py", line 43, in __init__
    self.packed_message = self.generate_packed_message()
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/message.py", line 46, in generate_packed_message
    self.payload = self.get_payload()
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/msgtypes.py", line 317, in get_payload
    label = b''.join(little_endian(bitstring.pack('8', c)) for c in self.label)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/msgtypes.py", line 317, in <genexpr>
    label = b''.join(little_endian(bitstring.pack('8', c)) for c in self.label)
  File "/usr/local/lib/python2.7/dist-packages/bitstring.py", line 4224, in pack
    s._append(BitStream._init_with_token(name, length, value))
  File "/usr/local/lib/python2.7/dist-packages/bitstring.py", line 1224, in _init_with_token
    b = cls(**{name: int(value), 'length': token_length})
ValueError: invalid literal for int() with base 10: '['

I try with 2 bulb parameter:

 python2 blink.py 2
Discovering lights...
Traceback (most recent call last):
  File "blink.py", line 72, in <module>
    main()
  File "blink.py", line 23, in main
    devices = lifx.get_lights()
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/lifxlan.py", line 49, in get_lights
    responses = self.broadcast_with_resp(GetService, StateService)
  File "/usr/local/lib/python2.7/dist-packages/lifxlan-0.2.3-py2.7.egg/lifxlan/lifxlan.py", line 203, in broadcast_with_resp
    raise WorkflowException('Did not receive {} in response to {}'.format(str(response_type), str(msg_type)))
lifxlan.device.WorkflowException: Did not receive <class 'lifxlan.msgtypes.StateService'> in response to <class 'lifxlan.msgtypes.GetService'>

You talk about route ...

My route table under linux is:
Destination     Gateway      Genmask         Indic Metric Ref    Use Iface
default         192.168.1.5    0.0.0.0         UG    202    0        0 eth0
192.168.1.0    *               255.255.255.0   U     202    0        0 eth0

my router is 192.168.1.5

Thanks for your help in advance

**Comment by mclarkk** [comment]
Hi! I was not able to reproduce this issue with my bulbs. I have a couple of questions for you:

How many lights do you have? 
What are the names of your lights?
How did you install `lifxlan`?

**Comment by j6k4m8** [comment]
Experiencing the same issue in Py 3.6. `pip install lifxlan` with 3 bulbs (all have spaces in their name labels)

**Comment by mclarkk** [comment]
@j6k4m8 Which of the issues are you experiencing?

**Comment by mikevador02** [comment]
Hello thanks for your response mclarkk, for my side i had re install version of raspian jessie instead de last version, and now it's work.

**Comment by j6k4m8** [comment]
@mclarkk was getting a WorkflowException. Was able to get it to work by running a bunch of times (a try/catch inside a loop)... After enough tries, it started finding lights successfully.
